### ISSUE TITLE
Rejected preflight OPTIONS requests

### ISSUE THREAD

**Issue by opoto** [Jorl17/open-elevation#11]
Hello
Using public API's POST requests in cross site javascript is failing because the preflight OPTIONS request is rejected with error 400.
Looking at the implementation, I think the preflight OPTIONS should not be treated as GET, because GET expects a query string and returns data, while OPTIONS should not parse input data, and should not return elevation data: it should only return the CORS headers.
Sample reproducing the error: https://jsfiddle.net/dn3nLywj/
Thanks for this great tool & service anyway

**Comment by opoto** [comment]
Ok, I found the trick to make it work: add dummy query string to the POST request URL. But this is an inefficient workaround, and does not match API doc.

**Comment by Jorl17** [comment]
Hi! Thank you for your report.

I have fixed CORS support for POST requests. Your fiddle was missing a `JSON.stringify`, but the [updated version here](https://jsfiddle.net/dn3nLywj/8/) is now working correctly.

Sadly, at the moment, you are probably experiencing very high latency. The service is under heavy usage by several users and, since I pay for it out of my own pocket, I cannot currently afford to upgrade the hardware.

Cheers! Feel free to open another issue if you want.

**Comment by opoto** [comment]
Works great, thanks!
