### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by JEMAGO713** [Jorl17/open-elevation#18]
Good evening: When making requests to the server (I only use the post method), it returns a 500 error.
I wanted to know if it really is a 500 error, or is masking some denial of service to my IP.

Thank you very much and greetings

**Comment by Biorix** [comment]
Is there any news regarding this issue ? 
I have the same problem (error 504 and 502) even through the website

**Comment by Jorl17** [comment]
Hi.

For the better part of the last 2 years, the API has been completely overloaded (sadly, **very little comes in the way of donations,** and so I can't really pay for a more beefed up machine).

**As of two days ago, though, I have done some tweaks to the backend and the API should be handling the workload much better. Give it a try again!**

I will also be **pushing a series of updates to the repository and dockerhub, to modernize the project and make it work again.**

I will close this issue because I believe that the public API is now working, but feel free to reopen it if it is not. If you have issues setting up a local environment, please open a separate issue for that.
