### ISSUE TITLE
API speed

### ISSUE THREAD

**Issue by titou71** [Jorl17/open-elevation#20]
Hi,

I cannot get more than 1 answer per 20-25secondes. Is there any trouble from your side ?

Thank you in advance for your answer,

**Comment by XerxesNoble** [comment]
@titou71 - it's a free API, probably makes sense that they don't have global server redundancy or a traffic manager. If you are looking for speed, you might want to host the service yourself :)

**Comment by Jorl17** [comment]
Yes, there are problems. See https://github.com/Jorl17/open-elevation/issues/29#issuecomment-462154786 :)

**Comment by Jorl17** [comment]
Hi.

For the better part of the last 2 years, the API has been completely overloaded (sadly, **very little comes in the way of donations,** and so I can't really pay for a more beefed up machine).

**As of two days ago, though, I have done some tweaks to the backend and the API should be handling the workload much better. Give it a try again!**

I will also be **pushing a series of updates to the repository and dockerhub, to modernize the project and make it work again.**

I will close this issue because I believe that the public API is now working, but feel free to reopen it if it is not. If you have any other issues, please open a separate issue for that.
