### ISSUE TITLE
404: http://gisweb.ciat.cgiar.org/TRMM/SRTM_Resampled_250m/

### ISSUE THREAD

**Issue by OlafvdSpek** [Jorl17/open-elevation#21]
404: http://gisweb.ciat.cgiar.org/TRMM/SRTM_Resampled_250m/

https://github.com/Jorl17/open-elevation/blob/master/docs/host-your-own.md

**Comment by paulsUsername** [comment]
I have the same problem.

**Comment by salihyalcin** [comment]
Does anyone found a solution to come up with ?

**Comment by robinmoussu** [comment]
It should be updated in docs/host-your-own.md.

**Comment by Jorl17** [comment]
Hi,

Many links are outdated, and we have internally already collected new links and data for multiple resolutions. We have been taking much longer than expected, but there are baby steps towards making open-elevation usable again and “restarting the project”. We are gathering a team (where I work) geared towards working directly on the project and hope to have news in the coming months. These news will include a better, working server (without constant timeouts), higher resolutions (including 1-arc-second) and updated documentation, code and docker images.

I’m sorry for being so absent, but unfortunately something has to pay the bills. Hopefully our work on open-elevation in the coming months will help us move faster.

I cannot provide the links we have gathered yet due to pending licensing issues, but hope to be able to soon.

An additional thank you to everyone who has been contributing pull requests and being far more active here than I am.

**Comment by subbareddydagumati** [comment]
Any plans to add the new data links to the code?

**Comment by aryoxp** [comment]
> Yep the files are moved.
> 
> To get the W & SE Files quick use this Link:
> https://drive.google.com/drive/u/0/folders/0B_J08t5spvd8VWJPbTB3anNHamc
> 
> To get the NE File use this Link:
> http://srtm.csi.cgiar.org/wp-content/uploads/files/250m/SRTM_NE_250m_TIF.rar
> 
> The Files SE & W are also accessible over this URL:
> http://srtm.csi.cgiar.org/wp-content/uploads/files/250m/SRTM_W_250m_TIF.rar
> http://srtm.csi.cgiar.org/wp-content/uploads/files/250m/SRTM_SE_250m_TIF.rar

What does W, SE, NE mean for the files? I wonder which file covers Japan?

**Comment by dangelsaurus** [comment]
> > Yep the files are moved.
> > To get the W & SE Files quick use this Link:
> > https://drive.google.com/drive/u/0/folders/0B_J08t5spvd8VWJPbTB3anNHamc
> > To get the NE File use this Link:
> > http://srtm.csi.cgiar.org/wp-content/uploads/files/250m/SRTM_NE_250m_TIF.rar
> > The Files SE & W are also accessible over this URL:
> > http://srtm.csi.cgiar.org/wp-content/uploads/files/250m/SRTM_W_250m_TIF.rar
> > http://srtm.csi.cgiar.org/wp-content/uploads/files/250m/SRTM_SE_250m_TIF.rar
> 
> What does W, SE, NE mean for the files? I wonder which file covers Japan?

The file is named for the lower left corner. So a file named N30W120.tiff would span from 30 to 31 degrees latitude, and -120 to -119 degrees longitude. By default tiles are 1° by 1° and the coordinates are in WGS84.

**Comment by Jorl17** [comment]
Hi.

For the better part of the last 2 years, the API has been completely overloaded (sadly, **very little comes in the way of donations,** and so I can't really pay for a more beefed up machine).

**As of two days ago, though, I have done some tweaks to the backend and the API should be handling the workload much better. Give it a try again!**

I will also be **pushing a series of updates to the repository and dockerhub, to modernize the project and make it work again.**

I will close this issue because I believe that this issue is solved, but feel free to reopen it if it is not. If you have any other issues, please open a separate issue for that.
