### ISSUE TITLE
Failed building wheel for GDAL

### ISSUE THREAD

**Issue by paulsUsername** [Jorl17/open-elevation#23]
I keep getting the same error. The Docker installation won't work at all so I am trying without Docker. I am using a phyton virtual environment for the install.

I am getting the error on:

`pip install -r requirements.txt
 `

`
  Failed building wheel for GDAL
`

Error is:
`Command "/home/igor/python-environments/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-3713gqek/GDAL/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ffntlwsp/install-record.txt --single-version-externally-managed --compile --install-headers /home/igor/python-environments/env/include/site/python3.5/GDAL" failed with error code 1 in /tmp/pip-install-3713gqek/GDAL/`

Is there any solution to this?

**Comment by strobel1x** [comment]
https://gist.github.com/cspanring/5680334#gistcomment-1248874
This helped for me but installs another version than specified in the requirements.txt - therefore I modified it...

**Comment by Jorl17** [comment]
Hi.

For the better part of the last 2 years, the API has been completely overloaded (sadly, **very little comes in the way of donations,** and so I can't really pay for a more beefed up machine).

**As of two days ago, though, I have done some tweaks to the backend and the API should be handling the workload much better. Give it a try again!**

I will also be **pushing a series of updates to the repository and dockerhub, to modernize the project and make it work again.**

I will close this issue because I believe that this issue is solved, but feel free to reopen it if it is not. If you have any other issues, please open a separate issue for that.
