### ISSUE TITLE
Unable to access the Public API: ssl handshake, eof, timeout issues both public and locals

### ISSUE THREAD

**Issue by munawarabad** [Jorl17/open-elevation#29]
I am able to access other https based web-apis but getting errors here. Previously public API worked pretty reliably. I even set up the the local version and it gives similar errors. 

r = requests.get('https://api.open-elevation.com/api/v1/lookup?locations=20,20')
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fa1435015c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.open-elevation.com', port=443): Max retries exceeded with url: /api/v1/lookup?locations=20,20 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa1435015c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.open-elevation.com', port=443): Max retries exceeded with url: /api/v1/lookup?locations=20,20 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa1435015c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

**Comment by jhodgdon-drp** [comment]
Currently, if you click on the URL for "Try it Live" from the Open Elevation home page
https://api.open-elevation.com/api/v1/lookup?locations=41.161758,-8.583933
you get a 504 Gateway error.

**Comment by Developer66** [comment]
The open-elevation seems to be offline.
You have to host your own server, whether we like it or not. @see [https://github.com/Jorl17/open-elevation/issues/27](https://github.com/Jorl17/open-elevation/issues/27)

I added new download source for 250m, 90m and europa 30m data to my forked project.
https://github.com/Developer66/open-elevation

Hope this helps
Developer66

**Comment by Jorl17** [comment]
Hi all.

The open-elevation project is not offline. However, it is completely overhwelmed with thousands (or more?) of requests per second. Unfortunately, the current machine does not have the capacity to deal with more, and since the project is kept running by me (donations are very very very scarce, and unfortunately cannot cover the costs), I have been unable to upgrade it further.

It genuinely pains me that I have not had the proper time to reply in any of the communication channels -- be it here, or through the e-mail. This has been due to professional reasons. This situation will change in about 2 months time, where my professional standing will change. When that happens, I will thoroughly look at the much appreciated pull requests that have been submitted and I will also look into ways to improve the project -- though still constrained by my financial availability.

I would therefore advise you to be keeping an eye on the project in the next two months, and until then, to browse these issues.

I would finally like to very much thank all of those who have been providing help, links (the legality of which I still have to confirm, hence also my absence given professional legal constraints on "outside work"), and overall sense of community that open-source provides us with. A heartfealt thank you

So, I'll be seeing you all in much more detail in two months!

**Comment by jakehoward** [comment]
Hey @Jorl17 - hope you're well. How many requests are we talking? Have you put it behind something like CloudFlare or Fastly? that should drastically reduce the load on your server if you haven't.

**Comment by berndhahnebach** [comment]
any news about this?

**Comment by Paliking** [comment]
Hi, is there something new? I am getting 504 Gateway Time-out very often. Sometimes it works, so I guess the server is still overwhelmed, correct?

**Comment by Jorl17** [comment]
Hi.

For the better part of the last 2 years, the API has been completely overloaded (sadly, **very little comes in the way of donations,** and so I can't really pay for a more beefed up machine). The plans to have a team working on it, sadly didn't pan out.

**As of two days ago, though, I have done some tweaks to the backend and the API should be handling the workload much better. Give it a try again!**

I will also be **pushing a series of updates to the repository and dockerhub, to modernize the project and make it work again.**

I will close this issue because I believe that the public API is now working, but feel free to reopen it if it is not. If you have any other issues, please open a separate issue for that.
