### ISSUE TITLE
Fair use of api (max number of requests, max number of locations in parameter)

### ISSUE THREAD

**Issue by ghost** [Jorl17/open-elevation#3]
First off, I really like your project.

In order to not ruin it for everyone, I would like to ask how many requests I can make. On a, doing what everybody does basis, I would limit it to one per second. Is that fine with you?

The next question is how many locations I can put in the locations parameter. Or more specifically: What is the max client header buffer, if that is the limiting factor? I don't want to try around until I get a 400 or 414...

The background is, that I want to get elevation data for a bunch of coordinates (about 500 to 2000) every other week (approximately). Or is this something for what I should already set up my own server?

**Comment by Jorl17** [comment]
Hi!

Sorry for the long delay, but work is hectic, and that leaves little time for side-projects...

There is currently no limit, but I can tell you that we are currently averaging about 1-2 requests per second. If you could keep your requests below that, the server might hang-on and "survive".

I would very much like to improve our current system, but the maintenance and hosting costs are currently fully covered by me, and sadly I am not rich...

I am considering creating a system with API keys so that it is easier to manually throttle and/or warn clients. I understand that it might break people already using the API, but with the popularity that it is slowly (yet surely) gaining, I am afraid that what you mention here might happen: that someone might accidentally render the service unusable for others. An API key would help with that.

I would also suggest that you make requests which are geographically close to one another for maximum performance. The server caches the most recent tiles.

Regarding max client header buffer, we are currently forcing request lines to be at most 4096 bytes, but there are plans to extend this value and to provide a POST api. I just need to find more free time...though any PR's are welcome!

If you have any more questions, please do say!

**Comment by Jorl17** [comment]
Slight update on this: Due to high amounts of traffic, a rate limit has been imposed now: **1 req/sec for each IP.**

I have been looking into creating a commercial version of the platform so that I can improve the public version. As usage increases, the overall performance for everyone decreases, and that is not my goal.

**Comment by Jorl17** [comment]
Hi.

For the better part of the last 2 years, the API has been completely overloaded (sadly, **very little comes in the way of donations,** and so I can't really pay for a more beefed up machine).

**As of two days ago, though, I have done some tweaks to the backend and the API should be handling the workload much better. Give it a try again!**

I will also be **pushing a series of updates to the repository and dockerhub, to modernize the project and make it work again.**

I will close this issue because I believe that the public API is now working, but feel free to reopen it if it is not. If you have any other issues, please open a separate issue for that.
