### ISSUE TITLE
./create-tiles.sh not working

### ISSUE THREAD

**Issue by shrimpie1911** [Jorl17/open-elevation#31]
I'm new to open elevation. I have follow the tuto "hosting your own server". I've create a folder call "data" and put my tiff file directly into that. Then i laun ./create-tiles.sh /data/<filename> but i get error `./create-tiles.sh: ligne 6: $2 : variable sans liaison`. Can somene help please?

Thank you in advance for the help and sorry for my bad english.

**Comment by shrimpie1911** [comment]
Sorry my bad i need to precise the file.

**Comment by Developer66** [comment]
I have a working version here: https://github.com/Developer66/open-elevation...

**Comment by Jorl17** [comment]
Hi.

For the better part of the last 2 years, the API has been completely overloaded (sadly, **very little comes in the way of donations,** and so I can't really pay for a more beefed up machine).

**As of two days ago, though, I have done some tweaks to the backend and the API should be handling the workload much better. Give it a try again!**

I will also be **pushing a series of updates to the repository and dockerhub, to modernize the project and make it work again.**

I will close this issue because I believe that this issue is solved, but feel free to reopen it if it is not. If you have any other issues, please open a separate issue for that.
