### ISSUE TITLE
API not working through Python

### ISSUE THREAD

**Issue by julienmalard** [Jorl17/open-elevation#33]
Hello,

I am having some difficulties with the Python API. When sending the following cal (as an example; I get the same for any lat, long value):

`fp = requests.get('https://api.open-elevation.com/api/v1/lookup?locations=31.569,74.355', timeout=30)`

...I get the following error:

`requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

Oddly enough, the same call succeeds when I cut and paste it into a browser winder.

Am I missing anything?

(In case you are wondering, I am hopeing to integrate the open elevation API call into the [taqdir](https://taqdir.readthedocs.io/) climate change data management API.

Best, and many thanks for this tool,
Julien Malard

**Comment by rdvelazquez** [comment]
This is probably related to https://github.com/Jorl17/open-elevation/issues/29#issuecomment-462154786

**Comment by Jorl17** [comment]
This is definitelt related to #29 . as I have mentioned elsewhere, there is a team working on Open-Elevation right now so that we can **finally** offer a decent user experience in the future, as we had before the service got so popular.

I'm really sorry that we cannot match your expectations at the moment

**Comment by julienmalard** [comment]
Thank you! However, it seems to work manually in the browser...any idea why?

**Comment by Jorl17** [comment]
Hi.

For the better part of the last 2 years, the API has been completely overloaded (sadly, **very little comes in the way of donations,** and so I can't really pay for a more beefed up machine).

**As of two days ago, though, I have done some tweaks to the backend and the API should be handling the workload much better. Give it a try again!**

I will also be **pushing a series of updates to the repository and dockerhub, to modernize the project and make it work again.**

I will close this issue because I believe that the public API is now working, but feel free to reopen it if it is not. If you have any other issues, please open a separate issue for that.

**Comment by julienmalard** [comment]
Wow, many thanks @Jorl17 ! I just tried it in Python again and it works very well now.
