### ISSUE TITLE
Docker image doesn't reflect the latest source

### ISSUE THREAD

**Issue by huntc** [Jorl17/open-elevation#35]
I noticed that commit 48ec871 isn't included in the latest Docker publish. Would you be able to publish that please? Thanks for open-elevation.

**Comment by Jorl17** [comment]
Hi.

For the better part of the last 2 years, the API has been completely overloaded (sadly, **very little comes in the way of donations,** and so I can't really pay for a more beefed up machine).

**As of two days ago, though, I have done some tweaks to the backend and the API should be handling the workload much better. Give it a try again!**

I will also be **pushing a series of updates to the repository and dockerhub, to modernize the project and make it work again.**

I will close this issue because dockerhub will be updated _very_ soon. If you have any other issues, please open a separate issue for that.
