### ISSUE TITLE
Base data

### ISSUE THREAD

**Issue by flightltd** [Jorl17/open-elevation#36]
Hi,

Is this based on SRMT1 or SRMT3 or another data set?

Cheers,

Paddy

**Comment by Jorl17** [comment]
Hi. We are currently using the 250m SRTM dataset. Found, for example, here: https://srtm.csi.cgiar.org/wp-content/uploads/files/250m/SRTM_NE_250m_TIF.rar

On our public offering, we have no plans of using another dataset. We are nonetheless considering adding support for other datasets in a possible paid offering. Unfortunately, since donations are so rare, we need to find a way to make some money :)
