### ISSUE TITLE
example request with curl not working

### ISSUE THREAD

**Issue by jefflalonde** [Jorl17/open-elevation#38]
Hi,

I have tried the example request _curl https://api.open-elevation.com/api/v1/lookup\?locations\=10,10\|20,20\|41.161758,-8.583933_ and I get the  following response:

_\<html>
 \<head>\<title>502 Bad Gateway</title>\</head>
\<body bgcolor="white">
\<center>\<h1>502 Bad Gateway\</h1>\</center>
\<hr>\<center>nginx/1.13.5\</center>
\</body>
\</html>_

What am I doing wrong?
Thanks.

**Comment by shkarlsson** [comment]
I'm getting error 504:

<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.13.5</center>
</body>
</html>

**Comment by aryoxp** [comment]
If you directly open the URL: 

`https://api.open-elevation.com/api/v1/lookup?locations=10,10|20,20|41.161758,-8.583933`

using a web browser around this posting time, then it eventually a time out request.

I also tried it today (Sep 11, 2020), it was also returning error. It returned 504 error.
Probably the server was down or currently unable to handle your request.
It happened to me too, so I try to host the server myself on localhost and it works.
However, you need to do the setup by yourself and find a proper geotiff map that covers your area.
Setting up the server with Docker is the easiest approach to me.

PS: Request with cURL command line needs the backspace character on the URL to escape the question mark `?` and pipe `|` characters. But when testing it on a web browser, omit the backspace character from the URL.

**Comment by sfranklus** [comment]
docker run -t -i -v /data:/code/data openelevation/open-elevation /code/create-dataset.sh
--2020-11-13 12:16:00--  http://gisweb.ciat.cgiar.org/TRMM/SRTM_Resampled_250m/SRTM_NE_250m_TIF.rar
Resolving gisweb.ciat.cgiar.org (gisweb.ciat.cgiar.org)... 45.5.186.33
Connecting to gisweb.ciat.cgiar.org (gisweb.ciat.cgiar.org)|45.5.186.33|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-11-13 12:16:01 ERROR 404: Not Found.

**Comment by charlycou** [comment]
SRTM data are now located at [https://srtm.csi.cgiar.org/wp-content/uploads/files/250m/](https://srtm.csi.cgiar.org/wp-content/uploads/files/250m/). You can either change the download-srtm-data.sh script and rebuild your own image or download the data yourself and mount them on your container as described in the documentation.

**Comment by Jorl17** [comment]
Hi.

For the better part of the last 2 years, the API has been completely overloaded (sadly, **very little comes in the way of donations,** and so I can't really pay for a more beefed up machine).

**As of two days ago, though, I have done some tweaks to the backend and the API should be handling the workload much better. Give it a try again!**

I will also be **pushing a series of updates to the repository and dockerhub, to modernize the project and make it work again.**

I will close this issue because I believe that the public API is now working, but feel free to reopen it if it is not. If you have any other issues, please open a separate issue for that.
